@baseURL = http://localhost:8080/api/v1
### ONLY USER ENDPOINTS


### Sign in a new user
POST {{baseURL}}/users
content-type : application/json

{
    "username" : "testuser",
    "password" : "12345678"
}
### Log in of user
POST {{baseURL}}/users/auth/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "12345678"
}


### URL PARA PRUEBA DE AUTH
GET {{baseURL}}/users/auth
### URL PARA PRUEBA DE AUTH


### Log out of user
POST {{baseURL}}/users/auth/logout



### delete user
DELETE {{baseURL}}/users


# ENDPOINTS TO TASKS

### Get all task of user
GET {{baseURL}}users/:idUser/tasks
### Show details about id task
GET {{baseURL}}users/:idUser/tasks/:taskId
### Search a task in base name 
GET {{baseURL}}users/:idUser/tasks?search=taskTitle
### Create a new task
POST {{baseURL}}users/:idUser/tasks
###  UPDATE A TASK by ID
PATCH {{baseURL}}users/:idUser/tasks/:taskId
###  DELETE A TASK by ID
DELETE {{baseURL}}users/:idUser/tasks/:taskId


