@baseURL = http://localhost:8080/api/v1



### NEW TASKS
POST {{baseURL}}/tasks
content-type : application/json

{
    "title" :"DELETE ME 21" ,
    "status":"new",
    "description" :"This is a task ONLY TEST, to try create a new task",
    "createdAt": "2024-01-21T11:11:00Z",
    "updatedAt": "2024-01-21T11:11:00Z",
    "limitTime": null
}


### ALL TASKS (OF A USER LOGED)
GET {{baseURL}}/tasks


### GET TASKS IN BASE ID-TASKS
GET {{baseURL}}/tasks/03abd043-effa-11ef-ab16-0250c91cb3a6


### TASKS Search Tasks by title (optional)
GET {{baseURL}}/tasks?search=TITLE


### UPDATE TASK BY ID
PATCH  {{baseURL}}/tasks/03abd043-effa-11ef-ab16-0250c91cb3a6
content-type : application/json

{
    "status":"done",
    "updatedAt": "2024-04-24T06:15:00Z",
    "limitTime": null
}


### DELETE TASK BY ID-TASK
DELETE {{baseURL}}/tasks/6782af6f-f3cd-11ef-91bb-0250c91cb3a6